general:
  pytorch_and_numpy_seed: null # Seeds pytorch and numpy (but not the data generator). `null` for random seed

arch:
  type: "ddetr_v2"
  num_queries: 16
  d_model: 256
  d_detections: 3
  encoder:
    n_heads: 8
    n_layers: 6
    dim_feedforward: 2048
    dropout: 0.1
  decoder:
    n_heads: 8
    n_layers: 6
    dim_feedforward: 2048
    dropout: 0.1
  rp_flooding:
    d_radius: 4
  d_prediction_hidden: 128
  n_prediction_layers: 3
  with_state_refine: True
  two_stage: True
  false_detect_embedding: True

loss:
  type: "detr"
  c_loss_multiplier: 4
  return_intermediate: True
  contrastive_classifier: True

training:
  n_gradient_steps: 5000
  n_gradient_steps_phase1: 1000
  learning_rate: 0.00005
  batch_size: 2
  n_splits: 1
  reduce_lr_patience: 2500
  reduce_lr_factor: 0.25
  checkpoint_interval: 1000 # after how many gradient steps to save the weights
  device: "cuda" # can be 'cpu', 'cuda', or 'auto' (use GPU if available)

debug:
  print_interval: 100
  enable_plot: False
  plot_interval: 1000
  save_plot_figs: True
  save_plot_figs_interval: 1000
  print_reduce_lr_messages: True
  log_interval: 1000
  evaluate_gospa_interval: 500
